server:
  port: 8080

spring:
#  profiles:
#    active: local
  datasource:
    username: root
    password: password
    url: jdbc:mysql://aa8sq2323q9x70.cp9iagwfbcu2.us-east-1.rds.amazonaws.com/ebdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: liquibase/db.changelog-master.yaml
  application:
    name: auto-sale
logging:
  level:
    org:
      springframework:
        security: INFO
        boot:
          autoconfigure: error

---

#spring:
#  profiles: local
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/auto-sale?characterEncoding=utf8&createDatabaseIfNotExist=true&serverTimezone=UTC
#  liquibase:
#    contexts: local

#---
#
#spring:
#  profiles: ${spring.profiles.active}
#  datasource:
#    username: root
#    password: password
#    url: jdbc:mysql://aaf447vj4ci30n.cp9iagwfbcu2.us-east-1.rds.amazonaws.com/ebdb
#  liquibase:
#    contexts: dev
#
#---

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            clientId: 804471670901-q6t4rhcb8f161jeus6m70s7v8i6m71kr.apps.googleusercontent.com
#            clientSecret: wSqfNzNiTXH-UE43cBFbZmIM
#            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#            tokenName: oauth_token
#            authenticationScheme: query
#            clientAuthenticationScheme: form
#            scope: profile email
#            resource:
#              userInfoUri: https://www.googleapis.com/oauth2/v2/me
#              preferTokenInfo: false
